### ISSUE TITLE
Music Extraction 

### ISSUE THREAD

**Issue by Harley201** [DCxDemo/CTR-tools#1]
I have yet to find a program that can successfully extract the vab and seq file from CTR because its semi custom, I know it uses samples and sequences because we can extract individual samples using PSound but we cant extract the sequences/midi or samples/soundfonts from the game, I hope this becomes a thing

**Comment by DCxDemo** [comment]
it doesn't have midi instruments to be mapped to, only a sample to play. i just picked bass so it doesn't sound creepy with a default piano set.

**Comment by DCxDemo** [comment]
you can export music in r6
