### ISSUE TITLE
Model Export to Ply

### ISSUE THREAD

**Issue by Harley201** [DCxDemo/CTR-tools#2]
I think instead of exporting to Obj, which has less support for vertex shading/colours, you should make the model exporter export .Ply which allows both vertex shading/colours and UV Mapping for textures.

**Comment by DCxDemo** [comment]
Added.
Usage: model_reader somefile.lev ply

It has a major downside of single mesh per file, though.

**Comment by Harley201** [comment]
.ply export isn't working, it'll say it's done but won't export any file

**Comment by DCxDemo** [comment]
ok so ply file was put in current path set in cmd, which most probably was C:\Users\<your_username>. by the time i tested it, i used a bat file, so i guess environment path was set as bat's location. not really a bug i guess, but i changed that so it strictly writes to app folder now.
