### ISSUE TITLE
TIM files

### ISSUE THREAD

**Issue by niko1point0** [DCxDemo/CTR-tools#7]
I did not see a tool for reading TIM files, there is a github respository that is working on TIM files that are inside Crash Team Racing

https://github.com/tatref/libctr

I hope this is helpful

**Comment by DCxDemo** [comment]
look closer at ctrvram folder.

**Comment by niko1point0** [comment]
@DCxDemo After cloning the repo, I was able to compile ctrvram.exe. However, under the Releases tab of the github repo, I did not see ctrvram (which was where I originally looked). Can there be an updated release with ctrvram included and prebuilt?

**Comment by DCxDemo** [comment]
this is just a helper tool intended for research. it will be merged with model_reader when and if we'll find how exactly game uses vram data (materials/UV). you can't actually extract game textures without corresponding level/model file anyways, so i don't see a point to add ctrvram as a release tool.

**Comment by tatref** [comment]
@niko1point0 : the main goal of my repo is to create doc + kaitai stracut (formal description of the data files). I'm trying to track DCxDemo's work closely.

I did some work on the character files, but i think DCxDemo caught up in the last commits.

About the TIM/vram files, it's just 2 TIM files in a row, my repo just describe how to find the offsets: https://github.com/tatref/libctr/blob/master/graphviz/ctr_tim2x.png

**Comment by niko1point0** [comment]
Thank you for the information
