### ISSUE TITLE
How to View Characters

### ISSUE THREAD

**Issue by niko1point0** [DCxDemo/CTR-tools#8]
[ModelViewer.zip](https://github.com/DCxDemo/CTR-tools/files/3203802/ModelViewer.zip)

Inside this zip is a model loader that can read VRAM files and LEV files. Models can be loaded with UV coordinates, vertex colors, and textures. Sometimes the vertical scaling is incorrect. You can use RenderDoc, or another tool that injects into OpenGL, to extract the UV coordinates and textures. 

I am not the writer of this software, and I do not have the source code. If the UV coordinates for the models are extracted from this EXE (with RenderDoc), they might help you find the UVs inside the file format.

I hope this was helpful

**Comment by DCxDemo** [comment]
dude, please. join discord and ask questions there to find out what's known and what not.

**Comment by niko1point0** [comment]
Ok. Can you tell me where I can find the Discord URL?

**Comment by DCxDemo** [comment]
did you check this repo's main page?
